version: '3'
services:
  xmos-dev:
    image: masonjacob/xmos-dev:latest
    # image: ghcr.io/xmos/xcore_builder:v3
    entrypoint: /home/container/.docker/entrypoint.sh
    command: "sleep inf"
    volumes:
      - ./../:/home/container
      - shared_data:/home/shared
    devices:
      - /dev/bus/usb:/dev/bus/usb
    stdin_open: true
    tty: true
  gtkwave:
    image: hdlc/gtkwave
    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
      - shared_data:/home/shared
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer

volumes:
  shared_data:
